In [3]:
import numpy as np
import pandas as pd

In [49]:
#Reading Data
books = pd.read_csv('book Recomendation data/books.csv', low_memory=False)
users = pd.read_csv('book Recomendation data/users.csv')
ratings = pd.read_csv('book Recomendation data/ratings.csv')

In [50]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [7]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [8]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [9]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [11]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [12]:
books.duplicated().sum()

0

In [13]:
ratings.duplicated().sum()

0

In [14]:
users.duplicated().sum()

0

In [15]:
#merging ratings and books based on ISBN column
ratings_with_name = ratings.merge(books,on='ISBN')

In [16]:
#counting the no.of ratings for each book
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [17]:
#changing datatype of book-rating col to int to perform aggregate functions
ratings_with_name['Book-Rating'] = pd.to_numeric(ratings_with_name['Book-Rating'], errors='coerce')

In [18]:
#books with avg rating
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'}, inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [19]:
#merging no.of ratings and average ratings
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [20]:
#taking top 250 books with highest average rating
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)
popular_df

,Book-Title,num_ratings,avg_rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [21]:
#displaying popular df with specified columns
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_rating']]
popular_df

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

In [22]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'

In [23]:
#displaying users index who have read more than 250 books
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
reading_users = x[x].index
reading_users

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [24]:
#displaying the reading users with specified columns from merged table using ratings and books df
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(reading_users)]
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [25]:
#taking books with no.of ratings more than 50
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [26]:
#displaying famous books with columns with filter ratings
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [27]:
#creating pivot table with index,columns and values as specified
pt = final_ratings.pivot_table(index='User-ID',columns='Book-Title',values='Book-Rating')
pt

Book-Title,1984,1st to Die: A Novel,2nd Chance,4 Blondes,A Bend in the Road,A Case of Need,"A Child Called \It\"": One Child's Courage to Survive""",A Civil Action,A Day Late and a Dollar Short,A Fine Balance,...,Winter Solstice,Wish You Well,Without Remorse,"Wizard and Glass (The Dark Tower, Book 4)",Wuthering Heights,Year of Wonders,You Belong To Me,Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,Zoya,"\O\"" Is for Outlaw"""
User-ID,,,,,,,,,,,,,,,,,,,,,
254,9.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2276,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2766,NaN,NaN,NaN,NaN,7.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN
3363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274308,NaN,NaN,0.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
275970,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN
277427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277639,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278418,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#filling empty values with 0's
pt.fillna(0,inplace=True)

In [29]:
pt

Book-Title,1984,1st to Die: A Novel,2nd Chance,4 Blondes,A Bend in the Road,A Case of Need,"A Child Called \It\"": One Child's Courage to Survive""",A Civil Action,A Day Late and a Dollar Short,A Fine Balance,...,Winter Solstice,Wish You Well,Without Remorse,"Wizard and Glass (The Dark Tower, Book 4)",Wuthering Heights,Year of Wonders,You Belong To Me,Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,Zoya,"\O\"" Is for Outlaw"""
User-ID,,,,,,,,,,,,,,,,,,,,,
254,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2276,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2766,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0
3363,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274308,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
275970,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278418,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
#importing cosine library
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [31]:
user_sim = 1 - pairwise_distances(pt.values,metric='cosine')
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.12087741, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.12087741, 1.        , ..., 0.        , 0.        ,
        0.05519574],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.05519574, ..., 0.        , 0.        ,
        1.        ]])

In [32]:
user_sim = 1 - pairwise_distances(pt.values,metric='cosine')
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.12087741, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.12087741, 1.        , ..., 0.        , 0.        ,
        0.05519574],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.05519574, ..., 0.        , 0.        ,
        1.        ]])

In [33]:
pd.DataFrame(user_sim).shape

(810, 810)

In [34]:
user_sim_df = pd.DataFrame(user_sim)

In [35]:
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,800,801,802,803,804,805,806,807,808,809
0,1.000000,0.000000,0.000000,0.113963,0.0,0.000000,0.000000,0.195832,0.000000,0.073324,...,0.133641,0.000000,0.000000,0.048247,0.000000,0.072985,0.173413,0.000000,0.0,0.000000
1,0.000000,1.000000,0.120877,0.000000,0.0,0.000000,0.343401,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.140975,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,0.000000,0.120877,1.000000,0.000000,0.0,0.138734,0.000000,0.000000,0.116618,0.056298,...,0.080805,0.000000,0.112360,0.000000,0.038723,0.000000,0.000000,0.000000,0.0,0.055196
3,0.113963,0.000000,0.000000,1.000000,0.0,0.057079,0.000000,0.089181,0.000000,0.000000,...,0.000000,0.106410,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
4,0.000000,0.000000,0.000000,0.000000,1.0,0.139347,0.000000,0.000000,0.000000,0.000000,...,0.117684,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.072985,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.066143,0.077970,0.000000,...,0.000000,0.000000,0.048776,0.000000,0.049117,1.000000,0.080119,0.125455,0.0,0.000000
806,0.173413,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.055878,0.000000,0.059623,...,0.058682,0.000000,0.000000,0.000000,0.000000,0.080119,1.000000,0.067174,0.0,0.000000
807,0.000000,0.000000,0.000000,0.000000,0.0,0.048271,0.000000,0.077638,0.000000,0.056806,...,0.000000,0.000000,0.058421,0.000000,0.044654,0.125455,0.067174,1.000000,0.0,0.000000
808,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000
809,0.000000,0.000000,0.055196,0.000000,0.0,0.000000,0.000000,0.094127,0.000000,0.000000,...,0.000000,0.072735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000

In [36]:
user_sim_df.index = pt.index.unique()
user_sim_df.index

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=810)

In [37]:
user_sim_df.columns = pt.index.unique()
user_sim_df.columns

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=810)

In [38]:
user_sim_df.iloc[0:15, 0:15]

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,6563,6575,7158,7286,7346
User-ID,,,,,,,,,,,,,,,
254,1.000000,0.000000,0.000000,0.113963,0.000000,0.000000,0.000000,0.195832,0.000000,0.073324,0.122679,0.064417,0.000000,0.000000,0.118197
2276,0.000000,1.000000,0.120877,0.000000,0.000000,0.000000,0.343401,0.000000,0.000000,0.000000,0.000000,0.022272,0.000000,0.000000,0.099759
2766,0.000000,0.120877,1.000000,0.000000,0.000000,0.138734,0.000000,0.000000,0.116618,0.056298,0.000000,0.067791,0.000000,0.096051,0.025409
2977,0.113963,0.000000,0.000000,1.000000,0.000000,0.057079,0.000000,0.089181,0.000000,0.000000,0.023275,0.065750,0.000000,0.000000,0.000000
3363,0.000000,0.000000,0.000000,0.000000,1.000000,0.139347,0.000000,0.000000,0.000000,0.000000,0.000000,0.101915,0.165574,0.000000,0.096667
4017,0.000000,0.000000,0.138734,0.057079,0.139347,1.000000,0.000000,0.071384,0.000000,0.046272,0.031672,0.105091,0.098057,0.000000,0.045799
4385,0.000000,0.343401,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153796
6251,0.195832,0.000000,0.000000,0.089181,0.000000,0.071384,0.000000,1.000000,0.000000,0.186387,0.139984,0.181916,0.000000,0.000000,0.071185
6323,0.000000,0.000000,0.116618,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.064338,0.000000,0.000000,0.000000,0.032836
6543,0.073324,0.000000,0.056298,0.000000,0.000000,0.046272,0.000000,0.186387,0.000000,1.000000,0.104179,0.208906,0.067879,0.131082,0.066379
6563,0.122679,0.000000,0.000000,0.023275,0.000000,0.031672,0.000000,0.139984,0.064338,0.104179,1.000000,0.104560,0.000000,0.000000,0.075144
6575,0.064417,0.022272,0.067791,0.065750,0.101915,0.105091,0.000000,0.181916,0.000000,0.208906,0.104560,1.000000,0.048514,0.000000,0.225976
7158,0.000000,0.000000,0.000000,0.000000,0.165574,0.098057,0.000000,0.000000,0.000000,0.067879,0.000000,0.048514,1.000000,0.000000,0.024508
7286,0.000000,0.000000,0.096051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.131082,0.000000,0.000000,0.000000,1.000000,0.054090
7346,0.118197,0.099759,0.025409,0.000000,0.096667,0.045799,0.153796,0.071185,0.032836,0.066379,0.075144,0.225976,0.024508,0.054090,1.000000

In [39]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:15, 0:15]

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,6563,6575,7158,7286,7346
User-ID,,,,,,,,,,,,,,,
254,0.000000,0.000000,0.000000,0.113963,0.000000,0.000000,0.000000,0.195832,0.000000,0.073324,0.122679,0.064417,0.000000,0.000000,0.118197
2276,0.000000,0.000000,0.120877,0.000000,0.000000,0.000000,0.343401,0.000000,0.000000,0.000000,0.000000,0.022272,0.000000,0.000000,0.099759
2766,0.000000,0.120877,0.000000,0.000000,0.000000,0.138734,0.000000,0.000000,0.116618,0.056298,0.000000,0.067791,0.000000,0.096051,0.025409
2977,0.113963,0.000000,0.000000,0.000000,0.000000,0.057079,0.000000,0.089181,0.000000,0.000000,0.023275,0.065750,0.000000,0.000000,0.000000
3363,0.000000,0.000000,0.000000,0.000000,0.000000,0.139347,0.000000,0.000000,0.000000,0.000000,0.000000,0.101915,0.165574,0.000000,0.096667
4017,0.000000,0.000000,0.138734,0.057079,0.139347,0.000000,0.000000,0.071384,0.000000,0.046272,0.031672,0.105091,0.098057,0.000000,0.045799
4385,0.000000,0.343401,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153796
6251,0.195832,0.000000,0.000000,0.089181,0.000000,0.071384,0.000000,0.000000,0.000000,0.186387,0.139984,0.181916,0.000000,0.000000,0.071185
6323,0.000000,0.000000,0.116618,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.064338,0.000000,0.000000,0.000000,0.032836
6543,0.073324,0.000000,0.056298,0.000000,0.000000,0.046272,0.000000,0.186387,0.000000,0.000000,0.104179,0.208906,0.067879,0.131082,0.066379
6563,0.122679,0.000000,0.000000,0.023275,0.000000,0.031672,0.000000,0.139984,0.064338,0.104179,0.000000,0.104560,0.000000,0.000000,0.075144
6575,0.064417,0.022272,0.067791,0.065750,0.101915,0.105091,0.000000,0.181916,0.000000,0.208906,0.104560,0.000000,0.048514,0.000000,0.225976
7158,0.000000,0.000000,0.000000,0.000000,0.165574,0.098057,0.000000,0.000000,0.000000,0.067879,0.000000,0.048514,0.000000,0.000000,0.024508
7286,0.000000,0.000000,0.096051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.131082,0.000000,0.000000,0.000000,0.000000,0.054090
7346,0.118197,0.099759,0.025409,0.000000,0.096667,0.045799,0.153796,0.071185,0.032836,0.066379,0.075144,0.225976,0.024508,0.054090,0.000000

In [40]:
user_sim_df.idxmax(axis=1)[-10:-1]

User-ID
271705    244736
273979    160819
274004    234623
274061    184299
274301    236340
274308    113817
275970     87974
277427    113817
277639    104429
dtype: int64

In [41]:
final_ratings[(final_ratings['User-ID']==274061) | (final_ratings['User-ID']==184299)]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
452,184299,0425115801,9,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
500,274061,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
1523,184299,0451166892,0,The Pillars of the Earth,Ken Follett,1996,Signet Book,http://images.amazon.com/images/P/0451166892.0...,http://images.amazon.com/images/P/0451166892.0...,http://images.amazon.com/images/P/0451166892.0...
1776,184299,0451167317,0,The Dark Half,Stephen King,1994,Signet Book,http://images.amazon.com/images/P/0451167317.0...,http://images.amazon.com/images/P/0451167317.0...,http://images.amazon.com/images/P/0451167317.0...
2355,184299,055310666X,0,False Memory,Dean R. Koontz,1999,Bantam Books,http://images.amazon.com/images/P/055310666X.0...,http://images.amazon.com/images/P/055310666X.0...,http://images.amazon.com/images/P/055310666X.0...
...,...,...,...,...,...,...,...,...,...,...
716232,274061,0373107048,0,Dark Paradise,Author Unknown,1984,Harlequin,http://images.amazon.com/images/P/0373107048.0...,http://images.amazon.com/images/P/0373107048.0...,http://images.amazon.com/images/P/0373107048.0...
817397,184299,0060541830,0,Congo,Michael Crichton,2003,Avon Books,http://images.amazon.com/images/P/0060541830.0...,http://images.amazon.com/images/P/0060541830.0...,http://images.amazon.com/images/P/0060541830.0...
827255,184299,0618346279,0,"The Return of the King (The Lord of the Rings,...",J. R. R. Tolkien,2003,Houghton Mifflin Company,http://images.amazon.com/images/P/0618346279.0...,http://images.amazon.com/images/P/0618346279.0...,http://images.amazon.com/images/P/0618346279.0...
863350,184299,0451139704,0,Cujo,Stephen King,1983,Signet Book,http://images.amazon.com/images/P/0451139704.0...,http://images.amazon.com/images/P/0451139704.0...,http://images.amazon.com/images/P/0451139704.0...
965893,184299,0739406388,0,Timeline,Michael Crichton,0,"Knopf, Alfred A",http://images.amazon.com/images/P/0739406388.0...,http://images.amazon.com/images/P/0739406388.0...,http://images.amazon.com/images/P/0739406388.0...

In [42]:
user_1=final_ratings[final_ratings['User-ID']==184299]

user_1

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
452,184299,0425115801,9,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
1523,184299,0451166892,0,The Pillars of the Earth,Ken Follett,1996,Signet Book,http://images.amazon.com/images/P/0451166892.0...,http://images.amazon.com/images/P/0451166892.0...,http://images.amazon.com/images/P/0451166892.0...
1776,184299,0451167317,0,The Dark Half,Stephen King,1994,Signet Book,http://images.amazon.com/images/P/0451167317.0...,http://images.amazon.com/images/P/0451167317.0...,http://images.amazon.com/images/P/0451167317.0...
2355,184299,055310666X,0,False Memory,Dean R. Koontz,1999,Bantam Books,http://images.amazon.com/images/P/055310666X.0...,http://images.amazon.com/images/P/055310666X.0...,http://images.amazon.com/images/P/055310666X.0...
4320,184299,0446364193,0,Along Came a Spider (Alex Cross Novels),James Patterson,1993,Warner Books,http://images.amazon.com/images/P/0446364193.0...,http://images.amazon.com/images/P/0446364193.0...,http://images.amazon.com/images/P/0446364193.0...
...,...,...,...,...,...,...,...,...,...,...
713953,184299,0385293925,0,Family Album,Danielle Steel,1985,Delacorte Press,http://images.amazon.com/images/P/0385293925.0...,http://images.amazon.com/images/P/0385293925.0...,http://images.amazon.com/images/P/0385293925.0...
817397,184299,0060541830,0,Congo,Michael Crichton,2003,Avon Books,http://images.amazon.com/images/P/0060541830.0...,http://images.amazon.com/images/P/0060541830.0...,http://images.amazon.com/images/P/0060541830.0...
827255,184299,0618346279,0,"The Return of the King (The Lord of the Rings,...",J. R. R. Tolkien,2003,Houghton Mifflin Company,http://images.amazon.com/images/P/0618346279.0...,http://images.amazon.com/images/P/0618346279.0...,http://images.amazon.com/images/P/0618346279.0...
863350,184299,0451139704,0,Cujo,Stephen King,1983,Signet Book,http://images.amazon.com/images/P/0451139704.0...,http://images.amazon.com/images/P/0451139704.0...,http://images.amazon.com/images/P/0451139704.0...
965893,184299,0739406388,0,Timeline,Michael Crichton,0,"Knopf, Alfred A",http://images.amazon.com/images/P/0739406388.0...,http://images.amazon.com/images/P/0739406388.0...,http://images.amazon.com/images/P/0739406388.0...

In [43]:
user_2=final_ratings[final_ratings['User-ID']==274061]

user_2

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
500,274061,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...,http://images.amazon.com/images/P/0425115801.0...
12888,274061,0439064864,0,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439064864.0...,http://images.amazon.com/images/P/0439064864.0...,http://images.amazon.com/images/P/0439064864.0...
22797,274061,0345342968,0,Fahrenheit 451,RAY BRADBURY,1987,Del Rey,http://images.amazon.com/images/P/0345342968.0...,http://images.amazon.com/images/P/0345342968.0...,http://images.amazon.com/images/P/0345342968.0...
25659,274061,067102423X,10,Bag of Bones,Stephen King,1999,Pocket,http://images.amazon.com/images/P/067102423X.0...,http://images.amazon.com/images/P/067102423X.0...,http://images.amazon.com/images/P/067102423X.0...
26878,274061,0385479565,0,The Hot Zone,Richard Preston,1995,Anchor,http://images.amazon.com/images/P/0385479565.0...,http://images.amazon.com/images/P/0385479565.0...,http://images.amazon.com/images/P/0385479565.0...
...,...,...,...,...,...,...,...,...,...,...
468423,274061,0440194903,0,When the Wind Blows,John Saul,1990,Dell,http://images.amazon.com/images/P/0440194903.0...,http://images.amazon.com/images/P/0440194903.0...,http://images.amazon.com/images/P/0440194903.0...
516624,274061,0451169514,10,It,Stephen King,1997,Signet Book,http://images.amazon.com/images/P/0451169514.0...,http://images.amazon.com/images/P/0451169514.0...,http://images.amazon.com/images/P/0451169514.0...
516683,274061,0670835382,10,Four Past Midnight,Stephen King,1990,Viking Books,http://images.amazon.com/images/P/0670835382.0...,http://images.amazon.com/images/P/0670835382.0...,http://images.amazon.com/images/P/0670835382.0...
524626,274061,0425119920,9,Strangers,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425119920.0...,http://images.amazon.com/images/P/0425119920.0...,http://images.amazon.com/images/P/0425119920.0...
716232,274061,0373107048,0,Dark Paradise,Author Unknown,1984,Harlequin,http://images.amazon.com/images/P/0373107048.0...,http://images.amazon.com/images/P/0373107048.0...,http://images.amazon.com/images/P/0373107048.0...

In [44]:
user_1['Book-Title']

452                                               Lightning
1523                               The Pillars of the Earth
1776                                          The Dark Half
2355                                           False Memory
4320                Along Came a Spider (Alex Cross Novels)
                                ...
713953                                         Family Album
817397                                                Congo
827255    The Return of the King (The Lord of the Rings,...
863350                                                 Cujo
965893                                             Timeline
Name: Book-Title, Length: 176, dtype: object

In [45]:
user_2['Book-Title']

500                                              Lightning
12888     Harry Potter and the Chamber of Secrets (Book 2)
22797                                       Fahrenheit 451
25659                                         Bag of Bones
26878                                         The Hot Zone
                                ...
468423                                 When the Wind Blows
516624                                                  It
516683                                  Four Past Midnight
524626                                           Strangers
716232                                       Dark Paradise
Name: Book-Title, Length: 75, dtype: object

In [46]:
def recommend(user1,user2):
    book_user1 = list(set(user_1['Book-Title']))
    book_user2 = list(set(user_2['Book-Title']))
    
    if len(book_user1)>len(book_user2):
        for book_name in book_user1:
          if book_name not in book_user2:
            print("Recommendation : ", book_name)
    elif len(book_user1)<len(book_user2):
         for book_name in book_user2:
          if book_name not in book_user1:
            print("Recommendation : ", book_name)
    else:
        print("No recommendation")

In [47]:
recommend(user_1,user_2)

Recommendation :  Wanderlust
Recommendation :  Bittersweet
Recommendation :  Wizard and Glass (The Dark Tower, Book 4)
Recommendation :  Mirror Image
Recommendation :  Ender's Game (Ender Wiggins Saga (Paperback))
Recommendation :  The Alienist
Recommendation :  C Is for Corpse (Kinsey Millhone Mysteries (Paperback))
Recommendation :  GARDEN OF SHADOWS (Dollanger Saga (Paperback))
Recommendation :  Naked
Recommendation :  Red Storm Rising
Recommendation :  E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))
Recommendation :  Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
Recommendation :  Rainbow Six
Recommendation :  The Bridges of Madison County
Recommendation :  Secrets
Recommendation :  The Angel of Darkness
Recommendation :  The Firm
Recommendation :  The Bonfire of the Vanities
Recommendation :  Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))
Recommendation :  The Bourne Supremacy
Recommendation :  Fast Food Nation: The Dark Side of the All-American Meal
Recommendation :  Gorky Park
Recommendation :  Kaleidoscope
Recommendation :  Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies
Recommendation :  Slow Waltz in Cedar Bend
Recommendation :  Pet Sematary
Recommendation :  Journey
Recommendation :  The Chamber
Recommendation :  The Great Gatsby
Recommendation :  Timeline
Recommendation :  Tell No One
Recommendation :  The Rainmaker
Recommendation :  Needful Things
Recommendation :  The Shipping News : A Novel
Recommendation :  The Perfect Storm : A True Story of Men Against the Sea
Recommendation :  Fatherhood
Recommendation :  Dances With Wolves
Recommendation :  The Cardinal of the Kremlin (Jack Ryan Novels)
Recommendation :  The Two Towers (The Lord of the Rings, Part 2)
Recommendation :  The Pillars of the Earth
Recommendation :  We'll Meet Again
Recommendation :  Jewel (Oprah's Book Club)
Recommendation :  Wicked: The Life and Times of the Wicked Witch of the West
Recommendation :  Devices and Desires
Recommendation :  Politically Correct Bedtime Stories: Modern Tales for Our Life and Times
Recommendation :  The Andromeda Strain
Recommendation :  Five Days in Paris
Recommendation :  A Painted House
Recommendation :  1984
Recommendation :  Message from Nam
Recommendation :  The Partner
Recommendation :  Postmortem
Recommendation :  Dark Angel
Recommendation :  The Cider House Rules
Recommendation :  Brave New World
Recommendation :  Vanished
Recommendation :  Pop Goes the Weasel
Recommendation :  Roses Are Red (Alex Cross Novels)
Recommendation :  A Bend in the Road
Recommendation :  The Runaway Jury
Recommendation :  Daddy
Recommendation :  The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure
Recommendation :  Evening Class
Recommendation :  Heartbeat
Recommendation :  Granny Dan
Recommendation :  Violets Are Blue
Recommendation :  Fried Green Tomatoes at the Whistle Stop Cafe
Recommendation :  The Villa
Recommendation :  Night Prey
Recommendation :  Coraline
Recommendation :  The Promise
Recommendation :  Executive Orders (Jack Ryan Novels)
Recommendation :  Last Man Standing
Recommendation :  Beloved (Plume Contemporary Fiction)
Recommendation :  A Virtuous Woman (Oprah's Book Club (Paperback))
Recommendation :  The Gift
Recommendation :  Without Remorse
Recommendation :  Let Me Call You Sweetheart
Recommendation :  The Fellowship of the Ring (The Lord of the Rings, Part 1)
Recommendation :  The Return of the King (The Lord of the Rings, Part 3)
Recommendation :  Into Thin Air : A Personal Account of the Mt. Everest Disaster
Recommendation :  Everything's Eventual : 14 Dark Tales
Recommendation :  Clear and Present Danger (Jack Ryan Novels)
Recommendation :  The Wedding
Recommendation :  Along Came a Spider (Alex Cross Novels)
Recommendation :  SHIPPING NEWS
Recommendation :  The Pelican Brief
Recommendation :  Family Album
Recommendation :  Silence of the Lambs
Recommendation :  The Deep End of the Ocean
Recommendation :  Tara Road
Recommendation :  FORREST GUMP (Movie Tie in)
Recommendation :  To Kill a Mockingbird
Recommendation :  Long After Midnight
Recommendation :  False Memory
Recommendation :  American Gods
Recommendation :  The Kiss
Recommendation :  Dawn (Cutler)
Recommendation :  Kiss the Girls
Recommendation :  The Hitchhiker's Guide to the Galaxy
Recommendation :  A Civil Action
Recommendation :  Fine Things
Recommendation :  Patriot Games (Jack Ryan Novels)
Recommendation :  You Belong To Me
Recommendation :  Good Omens
Recommendation :  No Greater Love
Recommendation :  Wild Animus
Recommendation :  Choke
Recommendation :  The Handmaid's Tale
Recommendation :  Debt of Honor (Jack Ryan Novels)
Recommendation :  High Fidelity
Recommendation :  Zoya
Recommendation :  Silent Witness
Recommendation :  Hearts In Atlantis
Recommendation :  Smilla's Sense of Snow
Recommendation :  A Time to Kill
Recommendation :  The Nanny Diaries: A Novel
Recommendation :  A Thousand Acres (Ballantine Reader's Circle)
Recommendation :  WLD ACCORDNG GARP
Recommendation :  Presumed Innocent
Recommendation :  The Five People You Meet in Heaven
Recommendation :  Foucault's Pendulum
Recommendation :  Christine
Recommendation :  The Bonesetter's Daughter
Recommendation :  Accident
Recommendation :  The Sum of All Fears (Jack Ryan Novels)
Recommendation :  The Alchemist: A Fable About Following Your Dream
Recommendation :  The Tao of Pooh
Recommendation :  The Bourne Ultimatum
Recommendation :  A Is for Alibi (Kinsey Millhone Mysteries (Paperback))